# Generated by Django 3.0.4 on 2020-04-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EcsServer',
            fields=[
                ('instance_id', models.CharField(db_column='Instance_ID', max_length=30, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(db_column='Instance_Name', max_length=30)),
                ('os_type', models.CharField(db_column='OS_Type', max_length=15)),
                ('os_name', models.CharField(db_column='OS_Name', max_length=30)),
                ('cpu', models.IntegerField(db_column='CPU')),
                ('memory', models.IntegerField(db_column='Memory')),
                ('primary_ip_address', models.CharField(blank=True, db_column='Primary_IP_Address', max_length=20, null=True)),
                ('public_ip_address', models.CharField(blank=True, db_column='Public_IP_Address', max_length=20, null=True)),
                ('expired_time', models.CharField(db_column='Expired_Time', max_length=50)),
                ('update_time', models.CharField(db_column='Update_Time', max_length=50)),
                ('belong_account', models.CharField(db_column='Belong_Account', max_length=30)),
            ],
            options={
                'db_table': 'ecs_server',
                'managed': False,
            },
        ),
    ]
