# Generated by Django 3.0.4 on 2020-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waf',
            fields=[
                ('domain_name', models.CharField(db_column='Domain_Name', max_length=40, primary_key=True, serialize=False)),
                ('instance_id', models.CharField(db_column='Instance_ID', max_length=30)),
                ('source_ip_addr', models.CharField(blank=True, db_column='Source_IP_Addr', max_length=255, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=255, null=True)),
                ('belong_account', models.CharField(db_column='Belong_Account', max_length=30)),
                ('update_time', models.DateTimeField(db_column='Update_Time')),
                ('is_delete', models.IntegerField()),
                ('is_update', models.IntegerField()),
            ],
            options={
                'db_table': 'waf',
                'managed': False,
            },
        ),
    ]
