# Generated by Django 3.0.4 on 2020-04-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_waf'),
    ]

    operations = [
        migrations.CreateModel(
            name='WafWhitelist',
            fields=[
                ('domain_name', models.CharField(db_column='Domain_Name', max_length=50, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(db_column='IP_Address', max_length=15)),
                ('is_delete', models.IntegerField()),
                ('update_time', models.DateTimeField(db_column='Update_Time')),
            ],
            options={
                'db_table': 'waf_whitelist',
                'managed': False,
            },
        ),
    ]
