# Generated by Django 3.0.4 on 2020-04-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_wafwhitelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdn',
            fields=[
                ('domain_name', models.CharField(db_column='Domain_Name', max_length=50, primary_key=True, serialize=False)),
                ('ssl_protocol', models.CharField(db_column='SSL_Protocol', max_length=5)),
                ('cdn_type', models.CharField(db_column='CDN_Type', max_length=14)),
                ('cname', models.CharField(db_column='Cname', max_length=255)),
                ('source_type', models.CharField(db_column='Source_Type', max_length=255)),
                ('source_content', models.CharField(db_column='Source_Content', max_length=255)),
                ('domain_status', models.CharField(db_column='Domain_Status', max_length=10)),
                ('belong_account', models.CharField(db_column='Belong_Account', max_length=30)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=40, null=True)),
                ('update_time', models.DateTimeField(db_column='Update_Time')),
                ('is_delete', models.IntegerField()),
            ],
            options={
                'db_table': 'cdn',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='wafwhitelist',
            options={},
        ),
    ]
