# Generated by Django 3.0.4 on 2020-04-28 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200428_0540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wafwhitelist',
            options={'managed': False},
        ),
    ]
